### ISSUE TITLE
[iOS] Player sometimes keeps seeking after view is unmounted

### ISSUE THREAD

**Issue by rclai** [TheWidlarzGroup/react-native-video#113]
This happens on remote video URLs.

Reproduction:
1. Create Video player with remote video URL (https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4)
2. Make it play (at this point you'll notice an activity indicator show up at the top left in your status bar, which indicates that it is buffering the video)
3. Unmount the Video player by either navigating away or change a state variable that causes the player to not show
4. The activity indicator at the top left in the status bar will keep spinning (it should disappear)

I think this happens when the network request hasn't finished responding and therefore the `AVPlayerItem` is stuck in seeking mode. I think that in the `removeFromSuperview` lifecycle, we need to call [`cancelPendingSeeks`](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayerItem_Class/index.html#//apple_ref/occ/instm/AVPlayerItem/cancelPendingSeeks) on the `AVPlayerItem`.

**Comment by rclai** [comment]
As a matter of fact, I noticed that the `AVPlayerLayer` and `AVPlayer` are cleaned up, but not the `AVPlayerItem`, so I'm thinking we need to do:

https://github.com/brentvatne/react-native-video/blob/3aa46875a58b857861377dc1528088ae027627e2/RCTVideo.m#L399-L405

```
[_playerItem cancelPendingSeeks];
[self removePlayerItemObservers]; // This line is already there
_playerItem = nil;
```

**Comment by kitolog** [comment]
+1 I got this bug too with remote urls

**Comment by andresn** [comment]
+1 I'm seeing this when transitioning to different pages via router. @brentvatne your thoughts?

**Comment by kitolog** [comment]
@andresn you can check video component unmount event and pause player. Works for me

**Comment by kshahkshah** [comment]
Yes, but is this going to blow up memory by pausing w/o unmounting. This seems like a serious issue if so.

**Comment by marlti7** [comment]
face the same problem

**Comment by yemi** [comment]
Im having problems with videos not unmounting correctly, or at least they seem to trigger the "cannot load more than 16 videos simultaneously even though only 1 video is mounted at a time.

Has anyone found a solution to the unmounting issue?

**Comment by pribeh** [comment]
Experiencing the same here. I'm not quite sure yet what isn't unmounting but there is a memory leak for sure after a video is played.

**Comment by maxschmeling** [comment]
I believe I've figured this out for my code, but I have a custom build of `react-native-video` that always uses `AVPlayerViewController` so that I can toggle the `controls` prop without a flicker (I plan to contribute a more general fix for that issue at some point, but haven't had time).

In `setSrc`, right after `[self removePlayerItemObservers]` I added:
```
if (_playerViewController != nil) {
  _playerViewController.player = nil;
}
```

For me, on an iPhone X running iOS 12.2, I could switch back and forth between two different videos to where `setSrc` was called 32 times without issue. The 33rd time would break. On an iPhone X running iOS 11.4.1, switching to where `setSrc` was called 16 times worked, but the 17th time would break.

With the addition of the lines above, I no longer have any issues switching between videos no matter how many times.

I would imagine in the main `react-native-video` code, a check could be done for both `_playerViewController` and `_playerLayer` to clear whichever one is being used.

**Comment by sebqq** [comment]
I'm encountering the same problem. The memory consumption is larger with every video which is played :(

**Comment by CHaNGeTe** [comment]
@jenshandersson is this solved by your PR? (v4.4.2)
https://github.com/react-native-community/react-native-video/pull/1614/files
Or should be added there also?
https://github.com/jenshandersson/react-native-video/blob/0a1557984e8920de49d372415016c8c4f5e46861/ios/Video/RCTVideo.m#L202

**Comment by jensellfors** [comment]
No that PR didn't fix this, looks like we only handle AVPlayerLayer in dealloc... I will submit a PR.

**Comment by CHaNGeTe** [comment]
Check on 4.4.3
