### ISSUE TITLE
[v5.0.2][Android] Controls sticking to screen on ScrollView/FlatList

### ISSUE THREAD

**Issue by jamsch** [TheWidlarzGroup/react-native-video#1744]
# Bug

Inserting a `<Video />` element with controls inside a FlatList can 1) stick the controls on the screen and 2) cause a native crash when scrolling too fast.

Pic below: A page with a few videos, note the controls are not attached to video element at all and are overlaying the text content.

![Selection_070_edit](https://user-images.githubusercontent.com/12927717/64748308-be24b280-d565-11e9-9c4c-8a228674d7ac.png)

## Crash log

Here's the last number of lines leading to a native crash:

```bash
2019-09-12 14:02:19.941 1403-24985/? W/AMessage: failed to post message as target looper for handler 0 is gone.
2019-09-12 14:02:19.960 1403-24991/? I/NuCachedSource2: caching reached eos.
2019-09-12 14:02:19.961 24005-24005/com.example.app W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
2019-09-12 14:02:19.962 1403-24994/? D/NuPlayer: onSetVideoSurface(0x99bcf100, no video decoder)
2019-09-12 14:02:19.972 1403-24987/? D/NuPlayerDriver: notifyListener_l(0xa07a3b00), (5, 1920, 1080), loop setting(0, 0)
2019-09-12 14:02:19.973 1403-24988/? D/GenericSource: stopBufferingIfNecessary_l, mBuffering=0
2019-09-12 14:02:19.973 1403-24987/? D/NuPlayerDriver: notifyListener_l(0xa07a3b00), (3, 100, 0), loop setting(0, 0)
2019-09-12 14:02:19.973 1403-24987/? D/NuPlayerDriver: notifyListener_l(0xa07a3b00), (1, 0, 0), loop setting(0, 0)
2019-09-12 14:02:19.975 24005-24005/com.example.app D/MediaPlayer: setSubtitleAnchor in MediaPlayer
2019-09-12 14:02:20.005 1403-16330/? D/NuPlayerDriver: reset(0xa07a3b00) at state 4
2019-09-12 14:02:20.005 1403-16330/? D/NuPlayerDriver: notifyListener_l(0xa07a3b00), (8, 0, 0), loop setting(0, 0)
2019-09-12 14:02:20.005 1403-24987/? D/NuPlayerDriver: notifyResetComplete(0xa07a3b00)
2019-09-12 14:02:20.005 1403-16326/? D/NuPlayerDriver: reset(0xa07a3b00) at state 0
2019-09-12 14:02:20.012 24005-24005/com.example.app D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-09-12 14:02:20.014 24005-24005/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 24005
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference
        at com.yqritc.scalablevideoview.ScalableVideoView.getCurrentPosition(ScalableVideoView.java:200)
        at android.widget.MediaController.setProgress(MediaController.java:438)
        at android.widget.MediaController.show(MediaController.java:358)
        at android.widget.MediaController.show(MediaController.java:314)
        at com.brentvatne.react.ReactVideoView$2.run(ReactVideoView.java:572)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
    
    
    --------- beginning of system
```

## Environment info

React native info output:

```bash
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 168.87 MB / 15.54 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.0, 27.0.1, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.60.5 => 0.60.5
```

Library version: 5.0.2

## Steps To Reproduce

1. Render at least one `<Video {...} />` component inside a FlatList
2. Start scrolling
3. App will likely crash, video player controls sticking to the screen while scrolling

Describe what you expected to happen:

Video player controls should stick to the player element

## Reproducible sample code

TODO

**Comment by hudrec** [comment]
Same issue !!!

**Comment by flexgrip** [comment]
Is this using native controls? Was wondering if android would get those soon.

**Comment by Tommoore96** [comment]
Same here, absolute nightmare

**Comment by SamiChab** [comment]
Same here
The error also happens on versions `5.0.1`, `5.0.0` and `5.1.0-alpha1`

**Comment by mtfranchetto** [comment]
Does anyone have a workaround for this?

**Comment by Deg5112** [comment]
this bug is an absolute joke
![Screenshot_11_18_19__2_39_PM](https://user-images.githubusercontent.com/13839383/69100080-38176300-0a11-11ea-9aa0-c29e0580ea33.png)

@scerelli 
i used your example but i have the same result.. I am on pixel with rn >61

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

i resynced gradle, rebuilt/run android same result

**Comment by codervss** [comment]
This is a big issue. Has anyone come up with a workaround or fix for this?

**Comment by abdulsami1105** [comment]
Any update on the issue?

**Comment by 349989153** [comment]
@scerelli Nice workaround! Thank you! At least the `video-control` doesn't fly around any more

**Comment by t-fritsch** [comment]
Can confirm @scerelli 's workaround works on RN 0.61.5 + react-native-video 5.0.2 when putting `<Video>`inside a `ScrollView`. Thanks a lot !

**Comment by luisfuertes** [comment]
With `react-native-video@5.0.2` and `react-native@0.62.2` on android, controls in FlatList not scroll with video :s controls are fixed on initial position.

**Comment by hienphung29** [comment]
@luisfuertes still the same bug with react-native-video@5.0.2 and @scerelli solution does not work for me.

**Comment by anshumanburman** [comment]
i too have the same issue, it is working fine in iOS but in android it is sticky in renderItem of flatlist. Please help me in this if anybody resolved this issue.?

**Comment by abhirajevolvier** [comment]
+1

**Comment by mykhailoperemitko** [comment]
I managed to resolve this issue by switching from MediaPlayer to ExoPlayer. You can find the instructions here #953

**Comment by umair25** [comment]
I had the same issue on IOS. I was using react-native-video-player. I wrapped the VideoPlayer component in a view and applied maxHeight and maxWidth property to the view. That fixed it.

**Comment by jakubgrzelak** [comment]
Any luck on this?

**Comment by firstfloordigital** [comment]
+1

**Comment by GuleriaAshish** [comment]
Anyone solved this issue? I am also facing the same

**Comment by dipankurXT** [comment]
Same issue
"react-native-video": "^5.2.0",
"react-native": "0.64.2",

**Comment by iasreact1** [comment]
@hueniverse  same problem facing the issue what to do to solve the issue please help

**Comment by lay-mand** [comment]
same problem here

**Comment by himanshut230** [comment]
same problem here

**Comment by Husk3r000** [comment]
any one fixed  this issue ?

**Comment by freeboub** [comment]
@Husk3r000 linked to MediaPlayer, not exoplayer. This issue is no more relevant
