### ISSUE TITLE
type error: null is not an object(evaluating 'RCTVideoinstance.Constant')

### ISSUE THREAD

**Issue by jeanechabaudis** [TheWidlarzGroup/react-native-video#1811]
# Bug

I am using react-native 0.61.2 and react-native-video 5.0.2 and when import the library and running emulator returning this error. I am user windows with android studio.

## Platform

* Android MediaPlayer

## Environment info

React native info output:

```bash
 // type error: null is not an object(evaluating 'RCTVideoinstance.Constant')
```

Library version: 5.0.2

## Steps To Reproduce

1. npm install --save react-native-video
2. react-native link react-native-video or react-native unlink react-native-video

## Image 
[
![74451366_2759493747429408_4476330897188061184_n](https://user-images.githubusercontent.com/8542195/68262576-a885b380-0011-11ea-87d1-c6f16e40b8b2.jpg)
](url)

**Comment by jeanechabaudis** [comment]
Hi friends, this error was fixed reinstalling the virtual device.

**Comment by bilalyaqoob** [comment]
@jeanechabaudis same issue and not solved after reinstalling

**Comment by umairhassan97** [comment]
I have a same issue but not yet solved

**Comment by atul-kaka** [comment]
Facing same. Not solve yet
