### ISSUE TITLE
[Android] ExoPlayer audio continues playing after Video component is unmounted

### ISSUE THREAD

**Issue by mk-nickyang** [TheWidlarzGroup/react-native-video#2913]
# Bug

[ExoPlayer Only] When the Video component gets re-mounted, it's possible that the previously destroyed video player is still playing audio. Can be reproduced in `5.2.0`, `5.2.1` and `6.0.0-alpha`.

Using the old Android MediaPlayer is fine.

## Platform
Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 104.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.03.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0 (Can also be reproduced in `5.2.1` and `6.0.0-alpha`)

## Steps To Reproduce

1. Clone https://github.com/mk-nickyang/react-native-video-exoplayer-zombie-audio
2. Follow [README](https://github.com/mk-nickyang/react-native-video-exoplayer-zombie-audio#readme) to set up the repo and ExoPlayer
3. 3 seconds after the video starts playing, `setKey` will force `<Video>` component to re-mount, listen for duplicate audio streams
4. Press the 'Unmount' button to unmount <Video> component and observe how audio steam is still playing despite there being no active video player

## Expected behaviour

No lingering audio after the Video component is unmounted

## Reproducible sample code

https://github.com/mk-nickyang/react-native-video-exoplayer-zombie-audio

## Video sample (volume up)

https://user-images.githubusercontent.com/29244509/200119368-6f2ca051-c556-435c-b9a5-2aa3651d4898.mov

**Comment by freeboub** [comment]
Thank you for the sample
This issue is due to asynchronism in     private void initializePlayer() {
developped with: new Handler().postDelayed(new Runnable() {
This is causing race condition in view management ...
No sort terms solution for this issue

**Comment by alexfoxy** [comment]
I have fixed with this component:
```
import React from 'react'
import RNVideo from 'react-native-video'

let ref: RNVideo | null

const Video = (props: RNVideo['props']) => {
  return <RNVideo
    ref={r => {
      if (!r) {
        // @ts-ignore setNativeProps does not exist on 'Video' .. but it does!
        if (ref?.setNativeProps) ref.setNativeProps({ paused: true })
      } else {
        ref = r
      }
    }}
    {...props}
  />
}

export default Video
```

**Comment by thomasyvert** [comment]
Any new issues ?
We still have the bug of the audio still playing even though the player component is well unmounted on the js side.

**Comment by WriteCodeEveryday** [comment]
Seeing this one as well on 5.2.1 and 6.0.0-beta.3

**Comment by freeboub** [comment]
this patch should fix the issue: https://github.com/react-native-video/react-native-video/pull/3629

**Comment by freeboub** [comment]
I tried to reproduce it on emulator, I didn't reproduce the issue.
To be retested with 6.0.0-beta.7
