### ISSUE TITLE
paused: true at start ignored

### ISSUE THREAD

**Issue by csakon** [TheWidlarzGroup/react-native-video#30]
I've set pause to true, but once a video loads, it ignores the setting and plays anyway. Toggling pause and play works fine once the video has started, but I want a video to load then remain paused at the first frame if pause is set to true.

**Comment by brentvatne** [comment]
Fixed in 0.3.3! Thanks

**Comment by card-b** [comment]
Still having this issue in the current version. The video plays on load whether I start in paused or not.
