### ISSUE TITLE
iOS 17.2 crash when controls={true}

### ISSUE THREAD

**Issue by abanobmikaeel** [TheWidlarzGroup/react-native-video#3329]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS

@react-navigation/native: 6.1.9
@react-navigation/native-stack: 6.9.16
expo: 49.0.15
react: 18.2.0
react-native: 0.72.6
react-native-safe-area-context: 4.7.4
react-native-screens: 3.27.0
react-native-video: 6.0.0-alpha.8

Library version: x.x.x
Device:  iPhone 15 Pro Max, iOS 17.2

Background: 
I do believe it's related to previous issues that happened like #3040 #3025 #2808 and #2773. I'm not well versed enough to narrow it down but I'm certain it's related to 

## Steps To Reproduce

1. In the example I added, when controls={true} for video component, and we navigate away to another screen a crash happens on iOS 17.2 
2. The video takes 4-5 seconds to become visible but it's right under the navigate button.
3. I will note that the video is an mp4
4. Crash details as follows

``` *** Terminating app due to uncaught exception
'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index
9223372036854775808 beyond bounds for empty array'
*** First throw call stack:
(
0   CoreFoundation                      0x000000010d308a09
__exceptionPreprocess + 242
1   libobjc.A.dylib                     0x0000000108d1d8b4
objc_exception_throw + 48
2   CoreFoundation                      0x000000010d1d92bf -[__NSArray0
objectEnumerator] + 0
3   AVKit                               0x000000010d982a31
-[AVMobileChromelessContentTabsViewController _activeContentTab] + 95
4   AVKit                               0x000000010d981fb6
-[AVMobileChromelessContentTabsViewController setCurrentContentTabIndex:]
+ 37
5   AVKit                               0x000000010d9827cf
-[AVMobileChromelessContentTabsViewController
scrollViewDidEndDecelerating:] + 244
6   videocrash                          0x00000001065e3e72 -[RNSScreen
traverseForScrollView:] + 706
7   videocrash                     <…>
```

## Expected behaviour

1. On Navigating away from a video
2. No crash occurs whether or not controls={true}

## Reproducible sample code
I created a minimal repro example. Can be found here https://github.com/abanobmikaeel/react-native-video-crash.

**Comment by maribeiroleya** [comment]
Same issue here

**Comment by hubertwang** [comment]
same here, any quick fix to this issue?

**Comment by KrzysztofMoch** [comment]
Currently no 😵‍💫
it's heavily complicated - will let know if anything new comes up

**Comment by abanobmikaeel** [comment]
@KrzysztofMoch I tried looking into the Swift file and I was completely lost unfortunately, you're our hope LOL. I do think this should be escalated in terms of priority since iOS 17.2 is being rolled out publicly and MANY users of this library will have crashes very soon unfortunately. 

Thanks for all the work that you guys are doing💚

As an aside
@hubertwang One temporary fix I've rolled out is to add this logic, basically manually implementing controls which isn't ideal but it's what's working currently. 

```
import { is_IOS_Under_17_2 } from "../helpers/Platform";
export default function VideoComponent({
  uri,
  showControls,
  onLoadStart,
  onLoadEnd,
  showThumbnailPlayButton,
}: any) {
  const [isPlaying, setIsPlaying] = useState(false);
  const togglePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  return (
    <>
      <Video
        source={{
          uri,
        }}
        resizeMode={ResizeMode.COVER}
        style={{ width: "100%", height: 300, flex: 1, zIndex: 1 }}
        paused={!isPlaying}
        controls={is_IOS_Under_17_2()}
        repeat={true}
        onLoadStart={() => onLoadStart()}
        onReadyForDisplay={() => onLoadEnd()}
      />

      <TouchableOpacity
        style={styles.topRightButtonStyle}
        onPress={togglePlayPause}
      >
        <Ionicons
          name={isPlaying ? "pause" : "play"}
          size={30}
          color={"white"}
        />
      </TouchableOpacity>
    </>
  );
}
```

**Comment by patrick-roon** [comment]
I went ahead an implemented some paired down custom controls for 17.2+. Wondering if there is an ETA on the long-term fix.

**Comment by KrzysztofMoch** [comment]
This issue is caused by react-native-screens. I opened an issue [here](https://github.com/software-mansion/react-native-screens/issues/1967).

**Comment by KrzysztofMoch** [comment]
As issue is not related with react-native-video I think we can close this. Progress  can be followed at [react-native-screen issue](https://github.com/software-mansion/react-native-screens/issues/1967)

**Comment by KrzysztofMoch** [comment]
Hey everyone, this issue will be fixed in next react-native-screens release!

**Comment by techlando** [comment]
Just updated to iOS 17.2 and the crash started on my app. Updated to react native screens to 3.29.0 and the issue has been resolved 🙏

**Comment by prashant6768** [comment]
I have updated react-native-screens to 3.29.0 but still getting the same error.

**Comment by uzun0ff** [comment]
> Just updated to iOS 17.2 and the crash started on my app. Updated to react native screens to 3.29.0 and the issue has been resolved 🙏

This has resolved the issue for me also. 🎉

I use Expo and also had to build a new build in order for the changes to have an effect.

**Comment by kmsayem12** [comment]
> Just updated to iOS 17.2 and the crash started on my app. Updated to react native screens to 3.29.0 and the issue has been resolved 🙏

@techlando Thank you. Work for me.
