### ISSUE TITLE
[BUG]: Portrait video auto crop to landscape when bad network

### ISSUE THREAD

**Issue by hieppd79** [TheWidlarzGroup/react-native-video#3713]
### What happened?

Portrait video auto crops to landscape when on a bad network connection.

**Bad network:**
![image](https://github.com/react-native-video/react-native-video/assets/161000547/128cbaff-fbad-4dab-8beb-de86954b8f1a)

**Normal network:**
![image](https://github.com/react-native-video/react-native-video/assets/161000547/da963f77-25a2-4faa-9276-70950e0486c2)

This is my component:
![image](https://github.com/react-native-video/react-native-video/assets/161000547/a4d3d15b-dbdb-4311-aba5-8d94a595b200)

Additional screenshot:
<img width="668" alt="image" src="https://github.com/react-native-video/react-native-video/assets/161000547/6f22bd02-d4f0-4242-9fb0-b7093b1c69dc">

### Steps to reproduce

1. Render a `<Video>` component with a portrait (vertical) video source.
2. Simulate or use a bad/slow network connection while the video loads/plays.
3. Observe that the portrait video is auto cropped to landscape, instead of keeping its portrait aspect ratio (as it does on a normal network).

### react-native-video version

6.0.0-beta.8

### Architecture

Old Architecture

**Comment by hieppd79** [comment]
And i have a question, When the network is slow, the video will stop for a certain frame. How can I capture that event and add it to the loading indicator?

**Comment by freeboub** [comment]
Currently there is no such event...
regarding to the ticket, I think the issue comes from you video. BTW, did you try to use resize mode : https://react-native-video.github.io/react-native-video/component/props#resizemode ? 
Is it android or ios or both ?

**Comment by hieppd79** [comment]
> Currently there is no such event... regarding to the ticket, I think the issue comes from you video. BTW, did you try to use resize mode : https://react-native-video.github.io/react-native-video/component/props#resizemode ? Is it android or ios or both ?


I have tried and only resizeMode.contain is suitable, but when the network is slow, this situation is quite uncomfortable for the user. I encounter it a lot on iOS, I will confirm later on Android.

**Comment by hieppd79** [comment]
> > Currently there is no such event... regarding to the ticket, I think the issue comes from you video. BTW, did you try to use resize mode : https://react-native-video.github.io/react-native-video/component/props#resizemode ? Is it android or ios or both ?
> 
> I have tried and only resizeMode.contain is suitable, but when the network is slow, this situation is quite uncomfortable for the user. I encounter it a lot on iOS, I will confirm later on Android.

"I think the issue comes from you video" Can you explain your speculation more clearly? @freeboub 
I don't play pre-recorded videos, I play stream with .m3u8

**Comment by freeboub** [comment]
@hieppd-slz It is possible that your m3u manifest contains bad informations, this is what I am suspecting.
If you have a sample m3u to share, I can have a look

**Comment by freeboub** [comment]
I think this issue is fixed in 6.1.2. please test this version, I will reopen if reproduced

**Comment by hieppd79** [comment]
![image](https://github.com/TheWidlarzGroup/react-native-video/assets/161000547/f5ce50f0-c7e8-4287-994b-6961e4c065ff)
@freeboub still exist on 6.1.2

**Comment by freeboub** [comment]
@hieppd-slz without a sample video to reproduce the issue, it cannot be investigated...

**Comment by hieppd79** [comment]
> @hieppd-slz without a sample video to reproduce the issue, it cannot be investigated...

![image](https://github.com/TheWidlarzGroup/react-native-video/assets/161000547/038c091e-a449-479b-aa72-368c71318d92)

do you want the master.m3u8 file for analysis?

**Comment by hieppd79** [comment]
@freeboub  I'm streaming now with `https://3bfa35a01653.ap-northeast-2.playback.live-video.net/api/video/v1/ap-northeast-2.299113936449.channel.OmJQKmFqSFi4.m3u8`

**Comment by freeboub** [comment]
I tried to put the video in the sample and force low profile video, but I don't reproduce the issue ... 
On emulator changing to "low profile" gives some video resize issue (but this is an emulator issue)
On my phone (oppo A57), switching to low profile gives a VIDEO_DECODING error, enabling `useTextureView={false}` fixed the issue.

Maybe you should try this useTextureView option ...

Bu I don't reproduce the resize issue you are showing :/

**Comment by hieppd79** [comment]
> I tried to put the video in the sample and force low profile video, but I don't reproduce the issue ... On emulator changing to "low profile" gives some video resize issue (but this is an emulator issue) On my phone (oppo A57), switching to low profile gives a VIDEO_DECODING error, enabling `useTextureView={false}` fixed the issue.
> 
> Maybe you should try this useTextureView option ...
> 
> Bu I don't reproduce the resize issue you are showing :/

it seems to be an android property, this phenomenon occurs on ios  and is reported by users,
one more information is, when this phenomenon occurs, src dimensions returned from onLoad is landscape, while the stream being played is portrait
@freeboub pls re-open this issue

**Comment by stee1ix** [comment]
@freeboub This issue is still happening on latest version. For some videos, it's happening every time, not caused by slow internet. I'm using `resizeMode="contain"`. Some videos are fine, some videos are squashed. This wasn't happening in v5, I'm trying to upgrade to v6 and this is a blocker.

**Comment by stee1ix** [comment]
I'm using `resizeMode="contain"`. Some videos are fine, some videos are squashed.

**Comment by stee1ix** [comment]
@hieppd79 Any luck here?

**Comment by TWG-AI** [comment]
Thanks for the continued reports on this! To move forward, we need a minimal reproduction case — the issue has been difficult to pinpoint without one.

Could you please provide:

1. **A sample video file or public URL** that reliably triggers the portrait→landscape cropping (even without a bad network, as @stee1ix reports it happens on certain videos regardless of network quality).
2. **Your exact `<Video>` component props** (especially `resizeMode`, `style` dimensions, and whether you're constraining the container).
3. **RN version** and **device/OS** details.

Without a reproducible case we can't isolate whether this is a manifest metadata issue, a track-selection bug, or a layout/`resizeMode` interaction. A public HLS URL or a small `.mp4` that always triggers the behavior would be ideal.
