### ISSUE TITLE
[BUG]: resizeMode glitch while move to another video

### ISSUE THREAD

**Issue by krisnapy** [TheWidlarzGroup/react-native-video#3892]
### What happened?

Video posters glitch when moving from one video to another. With `resizeMode` set to `CONTAIN` and a portrait-orientation video source, the poster appears stretched to landscape while buffering the next video.

Evidence:
![image](https://github.com/TheWidlarzGroup/react-native-video/assets/96037957/e39678b4-ec35-426c-8b87-b905e6f10ad5)

https://github.com/TheWidlarzGroup/react-native-video/assets/96037957/ad11eef6-09ac-400f-84c1-8a5b3ee1b842

### Steps to reproduce

1. Set up a video with `resizeMode` CONTAIN and a portrait-orientation video source.
2. Move to another video.
3. Observe the poster looks landscape while buffering to the other video.

### react-native-video version

6.1.2

### Platforms

Android

### OS version

All Android

### Device

Real device

### Architecture

Old Architecture

**Comment by freeboub** [comment]
Can you post you <Video usage (all the props) please ?
I think it is due to hideShutterView prop or shutterViewColor transparent... I don't think I will be able to fix it ...

**Comment by krisnapy** [comment]
Here is
```
     <Video
        ref={videoRef}
        source={{ uri }}
        style={sx(utility.flexOne)}
        resizeMode={ResizeMode.CONTAIN}
        paused={!playing}
        muted={!enableAudio}
        onLoad={data => {
          progressRef?.current?.stop()

          duration.current = data.duration
          forceShowThumbnail(data)
          onStart && onStart()
        }}
        onLoadStart={() => progressRef?.current?.start()}
        onEnd={onEnd}
        onBuffer={() => progressRef?.current?.start()}
        onProgress={e => {
          updateProgress(e)
          progressRef?.current?.stop()
        }}
        progressUpdateInterval={100}
        repeat={loop}
        ignoreSilentSwitch={playInBackground ? IgnoreSilentSwitchType.IGNORE : undefined}
        hideShutterView={true}
      />
```

**Comment by freeboub** [comment]
Thank you, so I am right, the issue is due to hideShutterView={true} Can you try to remove it ?

**Comment by krisnapy** [comment]
Looks flickering now after removed.

https://github.com/TheWidlarzGroup/react-native-video/assets/96037957/e41c6749-dced-4df7-aa97-a2d27bb1e513

**Comment by freeboub** [comment]
Did you also try with 6.2.0 ? I think there was a fix on this version if I remember well

**Comment by krisnapy** [comment]
Haven't tried it yet. Let me try it.

**Comment by krisnapy** [comment]
Tried 6.2.0 and the flickering is still happening.

**Comment by freeboub** [comment]
Ok, can you please provide a sample to reproduce the issue ?
I am not sure on how to handle this issue without a sample ...
Maybe you can try to use your streams with the sample app in the repo ?

**Comment by krisnapy** [comment]
After I tried to figure it out, it turned out that the problem was only with some of the videos. 
You can try the code bellow: 

```
import React, { useRef, useState } from 'react'
import { Pressable, View } from 'react-native'
import Video, { IgnoreSilentSwitchType, PosterResizeModeType, ResizeMode, VideoRef } from 'react-native-video'

function App(): JSX.Element {
  const videoRef = useRef<VideoRef>(null)

  const [currentUri, setCurrentUri] = useState(0)

  const uris = [
    'https://d1c40hpuz0tre6.cloudfront.net/stories/01J0311A6CNE1034G9GCNBG267.mp4',
    'https://d1c40hpuz0tre6.cloudfront.net/stories/01J02SR2R6FPGKAKYDJYZPWX14.mp4',
    'https://d1c40hpuz0tre6.cloudfront.net/stories/01HZRREJ1W14VPGD2XQZ2RRTQZ.mp4',
  ]

  return (
    <View style={{ flex: 1, backgroundColor: 'white' }}>
      <Pressable
        style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 4 }}
        onPress={() => {
          videoRef.current.seek(0)
          if (currentUri === uris.length - 1) return setCurrentUri(0)

          setCurrentUri(prev => prev + 1)
        }}
      />
      <Video
        ref={videoRef}
        source={{ uri:uris[currentUri] }}
        style={{ flex: 1 }}
        resizeMode={ResizeMode.CONTAIN}
        posterResizeMode={PosterResizeModeType.CONTAIN}
        progressUpdateInterval={100}
        ignoreSilentSwitch={IgnoreSilentSwitchType.IGNORE}
      />
    </View>
  )
}

export default App
```

Result: 

https://github.com/TheWidlarzGroup/react-native-video/assets/96037957/952a8249-d5fc-4981-abc5-5eb8993f4267

**Comment by krisnapy** [comment]
Is there any update?

**Comment by hieppd-slz** [comment]
same here `https://github.com/TheWidlarzGroup/react-native-video/issues/3713`

**Comment by hieppd79** [comment]
#3713 same here

**Comment by PauZeA** [comment]
I'm having the same issue, is there any update?

**Comment by quangtuan28200** [comment]
same issue, I'm using `v6.4.5`
I need to use `hideShutterView={true}` to avoid flickering when the video changes

I used `v6.3.0` before with props `useTextureView={true}` `hideShutterView={true}`, and the issue not happened but with `v6.4.5` and prop `viewType={ViewType.TEXTURE}` did seem not to work.

`resizeMode` will change to `STRETCH` when the video is changed
you can try setting `resizeMode={ResizeMode.STRETCH}`, the problem is gone but the video is stretched.


![Screenshot_2024-08-23-16-00-34-32_7aa77235eded29815713826f9744f8bd](https://github.com/user-attachments/assets/b30b782e-430f-4350-8c92-18682007f22f)

**Comment by kgaspar** [comment]
Can confirm I had the same problem of a stutter between video due to the view resizing. Stretch stops the stutter.

I noticed that it misbehaves when using the component without preset width/height, as shown in the example code in the documentation:

```
let styles = StyleSheet.create({
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
});

```
Any kind of dynamic width/height triggers the stutter. I rollbacked to v6.3.0 and the issue was gone.

**Comment by freeboub** [comment]
following PR (https://github.com/TheWidlarzGroup/react-native-video/pull/4185) Fix a glitch when playback source change, can you please test it ?
This is a big PR which change source management, I would really be happy to have some feedbacks !

**Comment by quangtuan28200** [comment]
I fixed that by not using `resizeMode` and using a `style` like this:
`style={{ width: '100%', aspectRatio: 16 / 9 }}`

**Comment by rayhanmhd123** [comment]
> following PR ([#4185](https://github.com/TheWidlarzGroup/react-native-video/pull/4185)) Fix a glitch when playback source change, can you please test it ? This is a big PR which change source management, I would really be happy to have some feedbacks !

Hi everyone,

I have tested this issue on version 6.10.0 and can confirm that it is still occurring. However, when tested on version 6.1.2, the issue did not appear.

Below is the source code example that reproduces the issue:

import React, { useEffect, useRef, useState } from 'react';
import SplashScreen from 'react-native-splash-screen';
import Video, { VideoRef } from 'react-native-video';

const videoArray = [
  require('./src/asset/broadchurch.mp4'),
  require('./src/asset/portrait.mp4'),
  require('./src/asset/videoplayback2.mp4'),
];

function App(): React.JSX.Element {
  const [currentVideoIndex, setCurrentVideoIndex] = useState(0);
  const videoRef = useRef<VideoRef>(null);

  useEffect(() => {
    SplashScreen.hide();
  }, []);

  const handleEnd = () => {
    setCurrentVideoIndex((prevIndex) => {
      const nextIndex = (prevIndex + 1) % videoArray.length;
      videoRef.current?.setSource(videoArray[nextIndex]);
      return nextIndex;
    }
    )
  };

  return (
    <Video
      ref={videoRef}
      hideShutterView={true}
      shutterColor="transparent"
      source={videoArray[currentVideoIndex]}
      onError={(e: any) => {
        console.error(e);
      }}
      onEnd={handleEnd}
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
      }}
      resizeMode={'contain'}
    />
  );
}

export default App;

I noticed that when using videos with the same aspect ratio as broadchurch.mp4, the issue does not occur. However, when using videos with different aspect ratios, the issue persists.

Please let me know if any further information is needed.

Thanks!

**Comment by rohit9625** [comment]
I can also face this issue when a portrait video is about to play. However, it doesn't seem to have happened for landscape videos.

**Comment by rohit9625** [comment]
Also, due to this flicker, the default controls appear for a fraction of a second even though I have `controls={false}`.

**Comment by TWG-AI** [comment]
Thanks for the detailed report and video evidence! This is a confirmed visual regression on Android — the `resizeMode=CONTAIN` setting isn't respected for the shutter/poster during a source change, causing a brief stretch to landscape.

**Root cause:** The issue is tied to `hideShutterView` + ExoPlayer's surface reuse during source changes. When the surface dimensions aren't reset before the next source starts loading, the old aspect ratio is retained for a frame.

**Workarounds (while this is being fixed):**
- Replace `resizeMode` with an explicit aspect ratio style: `style={{ width: '100%', aspectRatio: 9/16 }}` for portrait videos.
- Avoid `hideShutterView={true}` — the default shutter behavior masks the glitch at the cost of a black flash.

We're tracking this as a high-priority Android issue.
