### ISSUE TITLE
StatusBar is gone

### ISSUE THREAD

**Issue by shahen94** [TheWidlarzGroup/react-native-video#410]
When i play fullscreen video and then just press the `DONE` button my `statusBar` is gone throughout the entire app.

Platform: iOS 10, iOS 9
OS: MacOS

**Comment by mytream** [comment]
Have you solved this problem. I encountered the problem, too.
@olofd

**Comment by shahen94** [comment]
@mytream no, i'm not, I still have this issue

**Comment by joeferraro** [comment]
@shahen94 @mytream I experienced the same issue. Wrapping the `<Video/>` in a `<View>` with a `<StatusBar>` seems to resolve it:

```
<View>
        <StatusBar barStyle="light-content" />
        <Video source={{uri: this.props.url}} />
</View>
```

**Comment by xuanheScript** [comment]
@joeferraro I was RN0.39, using the method you said is invalid

**Comment by shahen94** [comment]
@jhabdas i've looked into code but unfortunately can't understand where is the issue, i'm far from obj c

**Comment by shahen94** [comment]
The issue has been fixed. PR is on pending stage
https://github.com/react-native-community/react-native-video/pull/532

**Comment by zakster12** [comment]
@shahen94 I still have the same bug. 
react-native-cli: 2.0.1
react-native: 0.46.4

Also I use the master like this: "react-native-video": "react-native-community/react-native-video#master",

**Comment by OmarBasem** [comment]
This bug still exists!

**Comment by bockc** [comment]
Still present in RN 0.61.4, why is this closed ?
