### ISSUE TITLE
[BUG]: om.brentvatne.react.test.ReactVideoPackage

### ISSUE THREAD

**Issue by CeJo1** [TheWidlarzGroup/react-native-video#4223]
### Version

6.6.4

### What platforms are you having the problem on?

Android

### System Version

Sonoma 14.6.1

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

I can't compile, I have this problem

android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:67: error: package com.brentvatne.react.test does not exist
import com.brentvatne.react.test.ReactVideoPackage;

  "react-native": "0.70.15"

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by KrzysztofMoch** [comment]
Can you try remove node_modules and android (by `cd android && ./gradlew clean`) cache and try again? I saw it once but then it resolved by it self ...

**Comment by CeJo1** [comment]
> Can you try remove node_modules and android cache and try again? I saw it once but then it resolve by it self ...

yes, I have removed everything, installed again and the error remains. I have tried many things, but what I have managed to detect is that the problem is the test class, but I don't know how to solve it.

**Comment by freeboub** [comment]
duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/4170
BTW, we need a sample to understand and fix the issue

**Comment by arvenjadeaguilar** [comment]
![Untitled](https://github.com/user-attachments/assets/f4801c42-c976-4476-8713-ee7b037c4996)

I think the issue was on the generated package list.. It imported the react-native-video as  import com.brentvatne.react.test.ReactVideoPackage; instead of import com.brentvatne.react.ReactVideoPackage;
