### ISSUE TITLE
Getting just a black container

### ISSUE THREAD

**Issue by luisbajana** [TheWidlarzGroup/react-native-video#821]
Hi everyone, thank you for this component. I'm having problems tho, I cannot reproduce any video in my application, I'm getting a div with a black background color.

I'm using this code: 

<Video
     source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
      rate={1.0}
      volume={1.0}
      muted={false}
      resizeMode="cover"
      repeat
      style={{ width: 300, height: 300 }}
     />

Part of my package JSON:

"react": "16.0.0-beta.5",
"react-native": "0.49.3",
"react-native-video": "^2.0.0"

![screen shot 2017-10-18 at 10 45 00 am](https://user-images.githubusercontent.com/1069185/31728279-763a300e-b3f1-11e7-8f82-12a2c7b2cf2e.png)

I tried for hours and couldn't make it work, hope someone could give me a hint.

Thanks in advance.

Luis.

**Comment by SaraChicaD** [comment]
I'm having the same issue

**Comment by enguerranws** [comment]
Can you try using HTTPS uri?

**Comment by luisbajana** [comment]
@enguerranws thank you so much! It is working! @SaraChicaD mirad

**Comment by SaraChicaD** [comment]
felicidades @luisbajana i still can't get it to do anything. I get a blank screen on android and the black box on ios. :'(

**Comment by luisbajana** [comment]
@SaraChicaD Did you run react-native link? I haven't test it on Android, but in iOS it's working. Buena suerte!

**Comment by SaraChicaD** [comment]
Hey yes, I did run react-native link, thx!

**Comment by fritsvt** [comment]
For me the sound plays, but I'm not getting any video output

**Comment by anantanandgupta** [comment]
create a ref and put this.player.seek(0) in componentWillMount ...

**Comment by deehuey** [comment]
I'm getting my local `require('./video.mp4')` is working fine on android, but on iphone, I'm just getting a box where the video should be playing. Same code on both...

**Comment by bachlx-bitmark** [comment]
I think black color is default background of container.
It(black) never display when I set other background color (white).

**Comment by isAlmogK** [comment]
I'm getting the same thing, has anyone got this working? Is this package even alive

**Comment by SaraChicaD** [comment]
@AlmogRnD did you change the URI to https? that made it work for me, but yea it's pretty much dead from what I can tell. I couldn't get it to work with anything but the link from the example.

**Comment by isAlmogK** [comment]
My uri is already https

**Comment by luisbajana** [comment]
It wasn't working again (very weird), then I found out that the problem was the simulator for some reason. Once I deployed the app into my phone the videos are working properly. And I'm uploading my own videos.

**Comment by luisbajana** [comment]
It wasn't working again (very weird), then I found out that the problem was the simulator for some reason. Once I deployed the app into my phone the videos are working properly.

**Comment by tommynordli** [comment]
I'm having the same issue, but only on iPhone 5. The same code works on other iPhones and Android phones. It's a local video, `require('./video.mp4')`

Edit: updated from `2.0.0` to `3.1.0` and the only difference is that there's a white background instead of black

Edit edit: made the video smaller, works fine now

**Comment by tommynordli** [comment]
Looks like it only worked in debug, not in production. Video is still not working on iPhone 5 for me
