### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by kibagateaux** [TheWidlarzGroup/react-native-video#865]
I've been through all solutions provided in [#438](https://github.com/react-native-community/react-native-video/issues/438), #597[](https://github.com/react-native-community/react-native-video/issues/597), and [#147](https://github.com/react-native-community/react-native-video/issues/147)

## Environment: 
Running on iOS
```
"react": "16.0.0-alpha.12"
"react-native": "0.48.3"
"react-native-video": "^2.0.0"
```

## Steps To Reproduce:
```
yarn add react-native-video
rnpm link
react-native run-ios
```

## Solutions I've Tried:
- Linking Binary Libraries manually
- Unlink -> uninstall -> clean project -> reinstall -> relink -> repackage
- Variations on `source` prop with `source={require('file-path.mp4')}` and `source={{uri: 'file-path'}}`

Don't much else I can try. Haven't tested on Android yet but that doesn't solve the problem on iOS either way. Any suggestions?

**Comment by noumantahir** [comment]
Having same issue here

**Comment by noumantahir** [comment]
fixed! just linked the library completely manually..both for iOS and tvOS targets...follow this link just in case anyone else have encounter the similar issue....https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by ansonyao** [comment]
Hey @noumantahir, I did this manually and it partially works. I can now run it in Xcode but it still does not run with react-native run-ios. Do you have same results?

**Comment by kibagateaux** [comment]
@noumantahir  I already tried manually linking following the docs and I was wondering if it was a CLI issue caused by using `rnpm link` as opposed to `react-native link` but I tried both and didn't see a difference. 

@ansonyao  Maybe try re-bundling from the CLI and running `react-native run-ios` again

**Comment by noumantahir** [comment]
@kibagateaux for me, the link command were useless, I had to drop them for manual linkage, worked for me, not sure what is the problem in your case.

@ansonyao results for both cases should be same as building from xcode running `react-native run-ios` are quite the same things, go with @kibagateaux  suggestion of rebundling

**Comment by guopeng1994** [comment]
hey guys! I use react-native link command can not link successfully. but i ran rnpm link, it linked successfully,so may be u guys can use rnpm to link this library.

**Comment by brianephraim** [comment]
I encountered this error.  I recently integrated Cocoapods, and noticed that the install of react-native-video added an entry to my Podfile. (maybe from `react-native link`).    So I ran `pod install`.  Now the Video component works.

**Comment by AustinHunt** [comment]
Don't forget to do `pod install`. It won't automatically do that step for you.

**Comment by alexfoxy** [comment]
is it necessary to use Pods with this plugin? It's not mentioned in the docs?

**Comment by cobarx** [comment]
It's possible to use either CocoaPods or link. Unless you have a good reason to need it (integrating React Native into an existing native app) link is the way to go.

When things go completely haywire, your best bet is to unlink and relink. If that fails, in Xcode delete RCTVideo.xcodeproj from Libraries and choose Remove Reference. Then right click Libraries -> Add Files to... -> navigate to ../node_modules/react-native-video/ios/RCTVideo.xcodeproj and Add it.

**Comment by damassi** [comment]
When using CocoaPods, one might have to link it manually in the podfile:

```rb
pod 'react-native-video', :path => File.join(node_modules_path, 'react-native-video/react-native-video.podspec')
```

**Comment by mortal-dog** [comment]
If you use react-native > 0.60
You need to run "pod install" under  /ios  folder, and there is no need to link or change anything else
