### ISSUE TITLE
Getting Errors after the react-native link cmd

### ISSUE THREAD

**Issue by phanir-menlo** [TheWidlarzGroup/react-native-video#875]
Hi Guys,

I am facing Issues while running the project.Installed React-native-video with version 1.0.0.Because am using the RN 0.39.0.after that I ran the project its showing error like "cannot read property constants of undefined ".Then I searched for a solution they told need to run command react-native-link.I ran this cmd.then tried to Run the app getting errors in Xcode(error is React/RCTViewManager.h file not found) how can i solve this errors.Could you guys please help me

**Comment by alexfoxy** [comment]
I have this same error

**Comment by cobarx** [comment]
Hopefully this is solved with newer React Native versions. Please reopen if it isn't.

**Comment by cinder92** [comment]
is not fixed, im using rn 0.59.1 with react native video 4.4.0
